sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

# docker and docker compose support
before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - mvn package
  - docker build -t michalix/vrdg .

after_script:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker push michalix/vrdg
    fi
